-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 16:48:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleInitial` VARCHAR(1) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Salary` DECIMAL(13,4) NULL,
  `SSN` VARCHAR(11) NULL,
  PRIMARY KEY (`EmployeeID`),
  UNIQUE INDEX `EmployeeID_UNIQUE` (`EmployeeID` ASC),
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_Deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_Deposit` (
  `EmployeeDepositID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `BankName` VARCHAR(45) NOT NULL,
  `RoutingNumber` INT(9) NOT NULL,
  `AccountNumber` INT(10) NOT NULL,
  `Amount` DECIMAL NOT NULL,
  PRIMARY KEY (`EmployeeDepositID`),
  UNIQUE INDEX `EmployeeDepositID_UNIQUE` (`EmployeeDepositID` ASC),
  INDEX `EmployeeID_idx` (`EmployeeID` ASC),
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Change_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Change_Log` (
  `ChangeLogID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  `Table` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  PRIMARY KEY (`ChangeLogID`),
  UNIQUE INDEX `ChangeLogID_UNIQUE` (`ChangeLogID` ASC),
  INDEX `EmployeeID_idx` (`EmployeeID` ASC),
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ClientID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ClientID`),
  UNIQUE INDEX `ClientID_UNIQUE` (`ClientID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_Business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_Business` (
  `BusinessID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `Name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`BusinessID`),
  UNIQUE INDEX `BusinessID_UNIQUE` (`BusinessID` ASC),
  INDEX `ClientID_idx` (`ClientID` ASC),
  CONSTRAINT `ClientID`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_Email` (
  `ClientEmailID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`ClientEmailID`),
  UNIQUE INDEX `ClientEmailID_UNIQUE` (`ClientEmailID` ASC),
  INDEX `ClientID_idx` (`ClientID` ASC),
  CONSTRAINT `ClientID`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_Phone` (
  `ClientPhoneID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `Number` INT(10) NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`ClientPhoneID`),
  UNIQUE INDEX `ClientPhoneID_UNIQUE` (`ClientPhoneID` ASC),
  INDEX `ClientID_idx` (`ClientID` ASC),
  CONSTRAINT `ClientID`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `ProjectID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `BusinessID` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Start` DATE NULL,
  `End` DATE NULL,
  `Due` DATE NULL,
  `Budget` DECIMAL(13,4) NULL,
  `Commission` DECIMAL(13,4) NULL,
  PRIMARY KEY (`ProjectID`),
  UNIQUE INDEX `ProjectID_UNIQUE` (`ProjectID` ASC),
  INDEX `ClientID_idx` (`ClientID` ASC),
  INDEX `BusinessID_idx` (`BusinessID` ASC),
  CONSTRAINT `ClientID`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BusinessID`
    FOREIGN KEY (`BusinessID`)
    REFERENCES `mydb`.`Client_Business` (`BusinessID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `PaymentID` INT NOT NULL,
  `ProjectID` INT NOT NULL,
  `ClientID` INT NOT NULL,
  `Amount` DECIMAL(13,4) NOT NULL,
  PRIMARY KEY (`PaymentID`),
  UNIQUE INDEX `PaymentID_UNIQUE` (`PaymentID` ASC),
  INDEX `ProjectID_idx` (`ProjectID` ASC),
  INDEX `ClientID_idx` (`ClientID` ASC),
  CONSTRAINT `ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`Project` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClientID`
    FOREIGN KEY (`ClientID`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_Project` (
  `EmployeeID` INT NOT NULL,
  `ProjectID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`, `ProjectID`),
  INDEX `ProjectID_idx` (`ProjectID` ASC),
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`Project` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
